In [4]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [5]:
list=["apple","orange","pineapple","apple"]

In [6]:
print(list)

['apple', 'orange', 'pineapple', 'apple']


In [7]:
len(list)

4

In [8]:
type(list)

list

In [9]:
arr1=[10,20,30,40]

In [10]:
print(arr1)
print(type(arr1))
print(arr1[2])
len(arr1)

[10, 20, 30, 40]
<class 'list'>
30


4

In [11]:
arr1.append(11)

In [12]:
# Add item to end
print(arr1)

[10, 20, 30, 40, 11]


In [13]:
#Remove item
arr1.pop(3)

40

In [14]:
print(arr1)

[10, 20, 30, 11]


In [15]:
# Clear Arr Data
arr1.clear()

In [16]:
print(arr1)
#again Add Values
arr1=[10,20,30,40]


[]


In [17]:
arr2=arr1.copy()
print(arr2)

[10, 20, 30, 40]


In [18]:
#Count the number of similar item
arr1.count(10)

1

In [19]:
arr1.extend(arr2)

In [20]:
print(arr1)

[10, 20, 30, 40, 10, 20, 30, 40]


In [21]:
#Retrive the Index Position of the item
arr1.index(40)

3

In [22]:
arr1.insert(16,50)

In [23]:
print(arr1)

[10, 20, 30, 40, 10, 20, 30, 40, 50]


In [24]:
# remove the item
arr1.remove(50)

In [25]:
print(arr1)

[10, 20, 30, 40, 10, 20, 30, 40]


In [26]:
arr1.sort()
print(arr1)

[10, 10, 20, 20, 30, 30, 40, 40]


In [27]:
arr1.reverse()
print(arr1)

[40, 40, 30, 30, 20, 20, 10, 10]


### Numpy Array Manipulation

In [28]:
import numpy as np

In [36]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
?arr1.astype

In [30]:
arr1.dtype

dtype('int64')

In [31]:
arr2=np.array([ (1,2,3,4,5), (6,7,8,9,10)])
print(arr2)
arr2.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [32]:
rows=4
cols=4
arr3 = [[j for j in range(cols)] for i in range(rows)] 
arr3

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]

In [33]:
arr4=np.array([[(1,2,3,4),(5,6,7,8)], [(1,2,3,4),(5,6,7,8)]])
print(arr4)
arr4.ndim

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


3

In [34]:
custom_array_4d = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
arr5=np.array([[ [[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]],
               [[[9, 10], [11, 12]],
                [[13, 14], [15, 16]]]])
print(arr5)
arr5.ndim

In [ ]:
array_4d = np.zeros((2, 3, 4, 5))
array_4d

### Exercise
1. Create an evenly- spaced array of numbers based on given start and stop values
2. Create an array of zeros that be filled with data later
3. Create an array of ones
4. Create an array of random, floats between zero and one
5. Create 1D array and insert the values 1,2,3,4,5 and access the following elements,

    * 1st element

    * 2nd element

    * Range of elements from 1st to 3rd

    * Range of elements from second element

    * Range of elements from index= -2


6. Create 2D array and try to access following elements,

    * 1st row and 2nd column element
    * 2nd row elements
    * 3rd row elements
    * range of elements in 1st and 2nd row with 2nd and 3rd column
    
7. create a 1D array make it within order by axis wise
8. Read 1D array and insert the values 1,9,2,5,3 and check whether the elements in array are greater than 5 and print those elements as seperate list(use Boolean masking)

In [ ]:
# 1.
print(np.linspace(0, 5, 5))

In [ ]:
# 2.
arr7=np.zeros(4)
arr7

In [ ]:
# 3.
arr8= np.ones(6)
arr8

In [ ]:
# 4.
arr9=np.random.random((2)) 
arr9

In [ ]:
# 5.
arr10=np.array([1,2,3,4,5])
arr10[0]
arr10[1]
arr10[0:2]
arr10[1:]
arr10[-2:]

In [ ]:
# 6.
arr11=np.array([ (1,2,3,4,5), (6,7,8,9,10)])
print(arr11)
arr11.ndim
arr11[0,1]
arr11[1]
arr11[:,2]
arr11[0:2,1:3]

In [ ]:
# 7.
arr12= np.arange(1,11)
arr12


In [35]:
# 8.
arr13= np.array([1,9,2,5,3])
check_array=arr13[arr13 >5]
check_array.tolist()

[9]